addons:
  sonarcloud:
    organization: "abcd12345"
    token:
      secure: "ZOHyAvxleVh3Nmj/kS7HExlRAXJC88fIB6ETuGLF+2FXf0GroyqizV5ZMO1Oe+/v1JZqapv3Gmf15WjwQlM+s+7Grj8Yb38dgK+3CO06beTEPsq+saPqbAa+ufgakk8pmqqYV3/PuYRg8Yk/Yo/kGehW+//EmZS8/D3UMloKBAc6T2scl6qhKA0GVl5aklaVsMbW0AG3MVkKE/CAXbmy8ojMC63sORaePwsUxy8uGS4Qobfal9TZwZVjw7aQZyNuXRazpKaeKp0lWweGtNXst2+jYsYOCr4YoyxBqefQBmnm5XbXnZKT/pbqcEKSdlegPVabybZZDSCPLe3V+INpJBZ25+E0ydDMJUkWAqDVuaYZabqnRVal2AeM8cv9B8sOU7w6WrRe4XJgKqGYzXWyy+lkLNuF+HJQn9xjccuxTpCZRlVIpfnMidvV0BagJrhGJYlb77QGTiVUA5EJL3UtOHkojRaU8qIA9DnEoHDF7LBd/tir8IZP7JLYrOX70OsiAbQp+QO8G7LlKerUYszT+zoRe2lOYmXEAjBwyz1WHLbkXF//R55ZIcbnVbXHiTwvHWjA1VIV1Yb2z9QhJp1TLBbGUasso/NlzY797yKCfTmn4PZ+0a7RjhcJi0VUIiFfbkpHjhxD/vreFxeieqwLiplo2MHfX15ADI8Jd0ZDjbg="
      
language: java
script:
  - ant dist
  - sonar-scanner